---
name: Build and Push Container Image

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore: ['**/README.md']
  schedule:
    - cron: '05 10 * * *'
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_DESC: "The operating system of my personal computer."
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"

jobs:
  build-and-push:
    name: Build and push container image
    runs-on: ubuntu-24.04
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup container storage
        uses: ublue-os/container-storage-action@main

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          oci: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
